"""Minimal Temporal-GNN and deterministic risk estimator.

The neural module is intentionally compact for reproducibility. The default
experiment uses the deterministic `RiskEstimator` because it does not require
long pretraining. The `TemporalGNN` class is included so that the repository
contains the model family described in the paper and can be extended to fully
supervised training from labels generated by `RiskLabeler`.
"""
from dataclasses import dataclass
import numpy as np
import torch
from torch import nn

class TemporalGNN(nn.Module):
    def __init__(self, in_dim: int, hidden_dim: int = 32):
        super().__init__()
        self.input_proj = nn.Linear(in_dim, hidden_dim)
        self.gru = nn.GRUCell(hidden_dim, hidden_dim)
        self.node_head = nn.Linear(hidden_dim, 1)
        self.cluster_head = nn.Linear(hidden_dim, 1)

    def forward(self, features_seq: torch.Tensor, adjacency_seq: torch.Tensor):
        # features_seq: [T, N, F], adjacency_seq: [T, N, N]
        T, N, _ = features_seq.shape
        h = torch.zeros(N, self.gru.hidden_size, device=features_seq.device)
        for t in range(T):
            x = torch.relu(self.input_proj(features_seq[t]))
            A = adjacency_seq[t]
            deg = A.sum(dim=-1, keepdim=True).clamp_min(1.0)
            neigh = (A @ x) / deg
            h = self.gru(neigh, h)
        node_risk = torch.sigmoid(self.node_head(h)).squeeze(-1)
        pooled = h.mean(dim=0)
        cluster_risk = torch.sigmoid(self.cluster_head(pooled)).squeeze(-1)
        return node_risk, cluster_risk, h

@dataclass
class RiskEstimator:
    """Fast deterministic risk estimator used by the minimal pipeline.

    It approximates short-horizon risk from residual energy, link quality,
    traffic pressure, and local topology. This makes the experiment runnable
    without long neural pretraining while preserving the paper's risk-aware
    control loop.
    """
    energy_dead_threshold: float = 0.05
    link_quality_min: float = 0.45

    def node_failure_risk(self, energy_norm: np.ndarray, mean_neighbor_lq: np.ndarray, traffic: np.ndarray, degree: np.ndarray) -> np.ndarray:
        low_energy = 1.0 - np.clip(energy_norm, 0, 1)
        poor_links = 1.0 - np.clip(mean_neighbor_lq, 0, 1)
        high_traffic = np.clip(traffic / (traffic.max() + 1e-9), 0, 1)
        sparse = 1.0 / (1.0 + degree)
        risk = 0.48 * low_energy + 0.28 * poor_links + 0.14 * high_traffic + 0.10 * sparse
        return np.clip(risk, 0, 1)

    def link_degradation_risk(self, link_quality: np.ndarray, energy_norm: np.ndarray) -> np.ndarray:
        poor = 1.0 - np.clip(link_quality, 0, 1)
        endpoint_energy = 1.0 - (energy_norm[:, None] + energy_norm[None, :]) / 2.0
        risk = 0.75 * poor + 0.25 * endpoint_energy
        np.fill_diagonal(risk, 1.0)
        return np.clip(risk, 0, 1)

    def cluster_instability(self, energy_norm: np.ndarray, alive: np.ndarray) -> float:
        vals = energy_norm[alive]
        if len(vals) < 2:
            return 1.0
        return float(np.clip(vals.std() / (vals.mean() + 1e-9), 0, 1))
